language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

sudo: false

# Command to install dependencies
install: "pip install --upgrade -r requirements/travis.txt"

# run tests
script:
  - make coverage

after_success:
  - coveralls 
